
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmsijphhzututcmzlhfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtc2lqcGhoenV0dXRjbXpsaGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NjE1NzYsImV4cCI6MjA1NTQzNzU3Nn0.e6MyIJ2j5ehDnnI-jAGY5toj7m6nqMVjAfpiHeOpN_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create storage buckets if they don't exist
(async () => {
  try {
    // Check if the buckets exist first to avoid unnecessary operations
    const { data: buckets } = await supabase.storage.listBuckets();
    
    // Create avatars bucket if it doesn't exist
    const avatarBucketExists = buckets?.some(bucket => bucket.name === 'avatars');
    if (!avatarBucketExists) {
      const { data, error } = await supabase.storage.createBucket('avatars', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 2, // 2MB limit
      });
      
      if (error) {
        console.error('Failed to create avatars bucket:', error);
      } else {
        console.log('Avatars bucket created successfully');
      }
    }
    
    // Create bubble-media bucket if it doesn't exist
    const mediaBucketExists = buckets?.some(bucket => bucket.name === 'bubble-media');
    if (!mediaBucketExists) {
      const { data, error } = await supabase.storage.createBucket('bubble-media', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 10, // 10MB limit for media files
      });
      
      if (error) {
        console.error('Failed to create bubble-media bucket:', error);
      } else {
        console.log('Bubble media bucket created successfully');
      }
    }
  } catch (err) {
    console.error('Error creating storage buckets:', err);
  }
})();
